{
 "title": "k6 reporting - InfluxQL",
 "description": "A dashboard for visualizing results from the k6.io load testing tool, using the InfluxDB exporter for the k6 test API https://test-api.loadimpact.com/",
 "time": { "from": "2024-03-27T03:53:30.000Z", "to": "2024-03-27T04:04:30.000Z" },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"value\") FROM \"http_reqs\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"value\") FROM \"errors\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "vus",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"vus\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MIN(\"value\") FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MAX(\"value\") FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Median",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MEDIAN(\"value\") FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P95",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 95) FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P80",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 80) FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P50",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 50) FROM \"http_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "all requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"value\") FROM \"cm_create_book_req_duration\" WHERE $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"value\") FROM \"cm_update_book_req_duration\" WHERE $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT MAX(\"value\") FROM \"cm_delete_book_req_duration\" WHERE $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT MAX(\"value\") FROM \"cm_get_book_req_duration\" WHERE $timeFilter GROUP BY time(1s)"
    }
   ]
  },
  {
   "title": "vu & requests & errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"value\" FROM \"vus\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"value\") FROM \"http_reqs\" WHERE $timeFilter GROUP BY time(1s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "query": "SELECT SUM(\"value\") FROM \"errors\" WHERE $timeFilter GROUP BY time(1s)"
    }
   ]
  },
  { "title": "Create Book api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"value\") FROM \"cm_create_book_reqs\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"value\") FROM \"cm_get_book_errors\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Avg",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MEAN(\"value\") FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MIN(\"value\") FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MAX(\"value\") FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Median",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MEDIAN(\"value\") FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P95",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 95) FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P90",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 90) FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P80",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 80) FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P70",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 70) FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P50",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 50) FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P30",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 30) FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "cm_create_book_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"cm_create_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  { "title": "Get Book api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"value\") FROM \"cm_get_book_reqs\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"value\") FROM \"cm_get_book_errors\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Avg",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MEAN(\"value\") FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MIN(\"value\") FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MAX(\"value\") FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Median",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MEDIAN(\"value\") FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P95",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 95) FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P90",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 90) FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P80",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 80) FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P70",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 70) FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P50",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 50) FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P30",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 30) FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "cm_get_book_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "query": "SELECT (\"value\") FROM \"cm_get_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  { "title": "Update Book api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"value\") FROM \"cm_update_book_reqs\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"value\") FROM \"cm_update_book_errors\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Avg",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "cm_update_book_req_duration",
     "query": "SELECT MEAN(\"value\") FROM \"cm_update_book_req_duration\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MIN(\"value\") FROM \"cm_update_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MAX(\"value\") FROM \"cm_update_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Median",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MEDIAN(\"value\") FROM \"cm_update_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P95",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 95) FROM \"cm_update_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P90",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 90) FROM \"cm_update_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P80",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 80) FROM \"cm_update_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P70",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 70) FROM \"cm_update_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P50",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 50) FROM \"cm_update_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P30",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 30) FROM \"cm_update_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "cm_update_book_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "query": "SELECT (\"value\") FROM \"cm_update_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  { "title": "Delete Book api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"value\") FROM \"cm_delete_book_reqs\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT SUM(\"value\") FROM \"cm_delete_book_errors\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Avg",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MEAN(\"value\") FROM \"cm_delete_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MIN(\"value\") FROM \"cm_delete_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MAX(\"value\") FROM \"cm_delete_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "Median",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT MEDIAN(\"value\") FROM \"cm_delete_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P95",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 95) FROM \"cm_delete_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P90",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 90) FROM \"cm_delete_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P80",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 80) FROM \"cm_delete_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P70",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 70) FROM \"cm_delete_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P50",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 50) FROM \"cm_delete_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "P30",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT PERCENTILE(\"value\", 30) FROM \"cm_delete_book_req_duration\" WHERE $timeFilter"
    }
   ]
  },
  {
   "title": "cm_delete_book_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "SELECT \"value\" FROM \"cm_delete_book_req_duration\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}