{
 "title": "k6 reporting - timescaledb",
 "time": { "from": "2024-04-10T06:31:44.000Z", "to": "2024-04-10T06:32:49.000Z" },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'http_reqs'; "
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'errors'; "
    }
   ]
  },
  {
   "title": "vus",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT ts, value FROM samples WHERE $__timeFilter(ts) AND metric = 'vus'; "
    }
   ]
  },
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'http_req_duration'; "
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'http_req_duration'; "
    }
   ]
  },
  {
   "title": "Median",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.5) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'http_req_duration'; "
    }
   ]
  },
  {
   "title": "P95",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.95) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'http_req_duration'; "
    }
   ]
  },
  {
   "title": "P80",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.80) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'http_req_duration'; "
    }
   ]
  },
  {
   "title": "P50",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.50) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'http_req_duration'; "
    }
   ]
  },
  {
   "title": "all requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \n    time_bucket('1 second', ts) AS time_window,\n    MAX(value) AS max_value\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'cm_create_book_req_duration'\nGROUP BY \n    time_window\n"
    },
    {
     "rawSql": "SELECT \n    time_bucket('1 second', ts) AS time_window,\n    MAX(value) AS max_value\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'cm_get_book_req_duration'\nGROUP BY \n    time_window\n"
    },
    {
     "rawSql": "SELECT \n    time_bucket('1 second', ts) AS time_window,\n    MAX(value) AS max_value\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'cm_update_book_req_duration'\nGROUP BY \n    time_window\n"
    },
    {
     "rawSql": "SELECT \n    time_bucket('1 second', ts) AS time_window,\n    MAX(value) AS max_value\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'cm_delete_book_req_duration'\nGROUP BY \n    time_window\n"
    }
   ]
  },
  {
   "title": "all requests",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \n    time_bucket('1 second', ts) AS time_window,\n    SUM(value) AS request\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'http_reqs'\nGROUP BY \n    time_window\n"
    },
    {
     "rawSql": "SELECT \n    time_bucket('1 second', ts) AS time_window,\n    SUM(value) AS vu\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'vus'\nGROUP BY \n    time_window\n"
    },
    {
     "rawSql": "SELECT \n    time_bucket('1 second', ts) AS time_window,\n    SUM(value) AS errors\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'errors'\nGROUP BY \n    time_window\n"
    }
   ]
  },
  { "title": "Create Book api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_reqs'; "
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_errors'; "
    }
   ]
  },
  {
   "title": "Avg",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Median",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.5) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P95",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.95) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P90",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.90) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P80",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.80) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P70",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.70) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P50",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.50) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P30",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.30) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_create_book_req_duration'; "
    }
   ]
  },
  {
   "title": "cm_create_book_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT \n    ts, value\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'cm_create_book_req_duration'\n\n"
    }
   ]
  },
  { "title": "Get Book api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_reqs'; "
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_errors'; "
    }
   ]
  },
  {
   "title": "Avg",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Median",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.5) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P95",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.95) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P90",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.90) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P80",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.80) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P70",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.70) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P50",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.50) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P30",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.30) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_get_book_req_duration'; "
    }
   ]
  },
  {
   "title": "cm_get_book_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT \n    ts, value\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'cm_get_book_req_duration'\n\n"
    }
   ]
  },
  { "title": "Update Book api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_reqs'; "
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_errors'; "
    }
   ]
  },
  {
   "title": "Avg",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Median",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.5) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P95",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.95) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P90",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.90) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P80",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.80) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P70",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.70) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P50",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.50) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P30",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.30) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_update_book_req_duration'; "
    }
   ]
  },
  {
   "title": "cm_update_book_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "SELECT \n    ts, value\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'cm_update_book_req_duration'\n\n"
    }
   ]
  },
  {
   "title": "Delete Book api",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true
  },
  {
   "title": "requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_reqs'; "
    }
   ]
  },
  {
   "title": "errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_errors'; "
    }
   ]
  },
  {
   "title": "Avg",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT AVG(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Min",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MIN(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Max",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT MAX(value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_req_duration'; "
    }
   ]
  },
  {
   "title": "Median",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.5) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P95",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.95) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P90",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.90) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P80",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.80) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P70",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.70) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P50",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.50) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_req_duration'; "
    }
   ]
  },
  {
   "title": "P30",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT percentile_cont(0.30) WITHIN group (ORDER BY value) FROM samples WHERE $__timeFilter(ts) AND metric = 'cm_delete_book_req_duration'; "
    }
   ]
  },
  {
   "title": "cm_delete_book_req_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "SELECT \n    ts, value\nFROM \n    samples \nWHERE \n    $__timeFilter(ts) \n    AND metric = 'cm_delete_book_req_duration'\n\n"
    }
   ]
  }
 ]
}