K6_WEB_DASHBOARD=true \
K6_WEB_DASHBOARD_HOST=localhost \
K6_WEB_DASHBOARD_PORT=5665 \
K6_WEB_DASHBOARD_PERIOD=5s \
K6_WEB_DASHBOARD_OPEN=false \
K6_WEB_DASHBOARD_EXPORT=report/k6-report.html \
k6 run run.js
