networks:
  grafana:

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    cpu_count: 2
    networks:
      - grafana
    ports:
      - "5432:5432"

  grafana:
    image: grafana/grafana:10.4.0
    networks:
      - grafana
    ports:
      - "3303:3000"
